# build 階段
FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/. ./
RUN npm run build

# 產出階段
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# nginx.conf is mounted directly
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
